-- Bootstrap exclusivo para Supabase local descartavel.
-- Reproduz somente o contrato estrutural necessario ao ciclo de pontos.

create schema if not exists private;

create table public.perfis (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nome text,
  perfil text not null check (perfil in ('administrador','operador','gerente','consulta')),
  gerente_nome text default '',
  rotas_permitidas text[] not null default '{}'
);

create table public.pontos (
  id bigint generated by default as identity primary key,
  nome_fantasia text not null unique,
  nome_dono text default '',
  telefone text default '',
  gerente text not null,
  modalidades text[] not null default '{}',
  possui_despesa text default 'nao',
  valor_despesa numeric(12,2) not null default 0,
  observacao text default ''
);

create table public.equipamentos (
  id bigint generated by default as identity primary key,
  nome text not null,
  localizacao text default '',
  status text default 'Disponível'
);

create table public.despesas_mensais (
  id bigint generated by default as identity primary key,
  ponto_id bigint references public.pontos(id) on delete restrict,
  competencia date not null,
  descricao text not null,
  tipo text not null default 'fixa',
  valor_previsto numeric(12,2) not null default 0,
  valor_real numeric(12,2) not null default 0,
  observacao text default '',
  criado_em timestamptz not null default now(),
  unique (ponto_id, competencia, descricao)
);

alter table public.perfis enable row level security;
alter table public.pontos enable row level security;
alter table public.equipamentos enable row level security;
alter table public.despesas_mensais enable row level security;

create or replace function private.perfil_atual()
returns text language sql stable security definer set search_path = public
as $$ select coalesce((select perfil from public.perfis where user_id = auth.uid()), 'consulta') $$;

create policy pontos_base on public.pontos for all to authenticated
using (private.perfil_atual() in ('administrador','operador','gerente'))
with check (private.perfil_atual() in ('administrador','operador','gerente'));
create policy equipamentos_base on public.equipamentos for all to authenticated
using (private.perfil_atual() in ('administrador','operador','gerente'))
with check (private.perfil_atual() in ('administrador','operador','gerente'));
create policy despesas_base on public.despesas_mensais for all to authenticated
using (private.perfil_atual() in ('administrador','gerente'))
with check (private.perfil_atual() in ('administrador','gerente'));

grant usage on schema public, private to authenticated;
grant select on public.perfis to authenticated;
grant select, insert, update, delete on public.pontos, public.equipamentos, public.despesas_mensais to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function private.perfil_atual() to authenticated;

insert into public.pontos (
  nome_fantasia, nome_dono, telefone, gerente, modalidades,
  possui_despesa, valor_despesa, observacao
) values (
  'PONTO EXISTENTE CONTROLE', 'Responsavel Local', '(00) 00000-0000', 'Rota Controle',
  array['Viapix','90 da Sorte'], 'sim', 123.45, 'Registro anterior a migration'
);

insert into public.equipamentos (nome, localizacao, status)
values ('EQUIPAMENTO CONTROLE', 'PONTO EXISTENTE CONTROLE', 'Em rota');

insert into public.despesas_mensais (ponto_id, competencia, descricao, valor_real)
select id, date '2026-07-01', 'DESPESA CONTROLE', 123.45
from public.pontos where nome_fantasia = 'PONTO EXISTENTE CONTROLE';
