-- BOOTSTRAP EXCLUSIVO PARA SUPABASE LOCAL DESCARTAVEL.
-- NAO E MIGRATION E NAO DEVE SER EXECUTADO EM PROJETOS REMOTOS.
-- Depois deste arquivo, aplique somente as migrations 202609010900 a 202609011010.

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'create role anon nologin';
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'create role authenticated nologin';
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'create role service_role nologin bypassrls';
  end if;
end;
$$;

create schema if not exists auth;

create table if not exists auth.users (
  id uuid primary key,
  instance_id uuid,
  aud text,
  role text,
  email text,
  encrypted_password text,
  email_confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function auth.uid()
returns uuid
language sql
stable
set search_path = pg_catalog
as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;

grant usage on schema auth to anon, authenticated, service_role;
grant execute on function auth.uid() to anon, authenticated, service_role;

create schema if not exists private;

create table public.perfis (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nome text,
  perfil text not null check (perfil in ('administrador', 'operador', 'gerente', 'consulta')),
  gerente_nome text default '',
  login_nome text,
  rotas_permitidas text[] not null default '{}'
);

create table public.pontos (
  id bigint generated by default as identity primary key,
  nome_fantasia text not null,
  gerente text not null default ''
);

create unique index pontos_nome_fantasia_normalizado_uidx
  on public.pontos (lower(btrim(nome_fantasia)));

create table public.equipamentos (
  id bigint generated by default as identity primary key,
  nome text not null,
  categoria text,
  quantidade integer not null default 1,
  localizacao text default '',
  patrimonio text default '',
  status text default 'Disponível',
  minimo integer not null default 1,
  observacao text default '',
  responsavel text default '',
  data_cadastro text default '',
  gerente_responsavel text default '',
  transferencia_status text default '',
  transferencia_enviada_em timestamptz,
  transferencia_recebida_em timestamptz
);

alter table public.perfis enable row level security;
alter table public.pontos enable row level security;
alter table public.equipamentos enable row level security;

create or replace function private.perfil_atual()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select p.perfil from public.perfis p where p.user_id = auth.uid()), 'consulta');
$$;

create or replace function private.gerente_atual()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select nullif(btrim(p.gerente_nome), '') from public.perfis p where p.user_id = auth.uid()),
    (select nullif(btrim(p.nome), '') from public.perfis p where p.user_id = auth.uid()),
    ''
  );
$$;

create policy perfis_base on public.perfis for select to authenticated
using (user_id = auth.uid() or private.perfil_atual() = 'administrador');
create policy pontos_base on public.pontos for select to authenticated
using (
  private.perfil_atual() in ('administrador', 'operador')
  or (
    private.perfil_atual() = 'gerente'
    and exists (
      select 1 from public.perfis p
      where p.user_id = auth.uid()
        and public.pontos.gerente = any(coalesce(p.rotas_permitidas, array[]::text[]))
    )
  )
);
create policy equipamentos_base_ler on public.equipamentos for select to authenticated
using (
  private.perfil_atual() in ('administrador', 'operador')
  or (
    private.perfil_atual() = 'gerente'
    and (
      gerente_responsavel = private.gerente_atual()
      or localizacao in (
        select pt.nome_fantasia from public.pontos pt
        where exists (
          select 1 from public.perfis p
          where p.user_id = auth.uid()
            and pt.gerente = any(coalesce(p.rotas_permitidas, array[]::text[]))
        )
      )
    )
  )
);
create policy equipamentos_base_escrever on public.equipamentos for all to authenticated
using (private.perfil_atual() in ('administrador', 'operador'))
with check (private.perfil_atual() in ('administrador', 'operador'));

grant usage on schema public, private to authenticated, service_role;
grant select on public.perfis, public.pontos to authenticated;
grant select, insert, update, delete on public.equipamentos to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function private.perfil_atual() to authenticated, service_role;
grant execute on function private.gerente_atual() to authenticated, service_role;
