-- Stock-ON - estrutura profissional inicial
-- Execute no SQL Editor do Supabase somente apos corrigir codigos duplicados.

begin;

create unique index if not exists equipamentos_patrimonio_unico
  on public.equipamentos (upper(trim(patrimonio)))
  where patrimonio is not null and trim(patrimonio) <> '';

create table if not exists public.perfis (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nome text,
  perfil text not null default 'consulta' check (perfil in ('administrador', 'operador', 'consulta')),
  criado_em timestamptz not null default now()
);

-- Preserva o acesso inicial durante a configuracao. Depois, ajuste os perfis no painel.
insert into public.perfis (user_id, nome, perfil)
select id, coalesce(raw_user_meta_data->>'name', email), 'administrador'
from auth.users
on conflict (user_id) do nothing;

create or replace function public.perfil_atual()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select perfil from public.perfis where user_id = auth.uid()), 'consulta');
$$;

create table if not exists public.despesas_mensais (
  id bigint generated by default as identity primary key,
  ponto_id bigint not null references public.pontos(id) on delete restrict,
  competencia date not null,
  descricao text not null,
  tipo text not null default 'fixa' check (tipo in ('fixa', 'variavel')),
  valor_previsto numeric(12,2) not null default 0,
  valor_real numeric(12,2) not null default 0,
  observacao text default '',
  criado_em timestamptz not null default now(),
  unique (ponto_id, competencia, descricao)
);

alter table public.equipamentos enable row level security;
alter table public.pontos enable row level security;
alter table public.historico_equipamentos enable row level security;
alter table public.historico_pontos enable row level security;
alter table public.perfis enable row level security;
alter table public.despesas_mensais enable row level security;

drop policy if exists equipamentos_ler on public.equipamentos;
drop policy if exists equipamentos_escrever on public.equipamentos;
drop policy if exists pontos_ler on public.pontos;
drop policy if exists pontos_escrever on public.pontos;
drop policy if exists historico_equip_ler on public.historico_equipamentos;
drop policy if exists historico_equip_escrever on public.historico_equipamentos;
drop policy if exists historico_pontos_ler on public.historico_pontos;
drop policy if exists historico_pontos_escrever on public.historico_pontos;
drop policy if exists perfis_ler on public.perfis;
drop policy if exists perfis_administrar on public.perfis;
drop policy if exists despesas_ler on public.despesas_mensais;
drop policy if exists despesas_escrever on public.despesas_mensais;

create policy equipamentos_ler on public.equipamentos for select to authenticated using (true);
create policy equipamentos_escrever on public.equipamentos for all to authenticated
  using (public.perfil_atual() in ('administrador','operador'))
  with check (public.perfil_atual() in ('administrador','operador'));
create policy pontos_ler on public.pontos for select to authenticated using (true);
create policy pontos_escrever on public.pontos for all to authenticated
  using (public.perfil_atual() in ('administrador','operador'))
  with check (public.perfil_atual() in ('administrador','operador'));
create policy historico_equip_ler on public.historico_equipamentos for select to authenticated using (true);
create policy historico_equip_escrever on public.historico_equipamentos for insert to authenticated
  with check (public.perfil_atual() in ('administrador','operador'));
create policy historico_pontos_ler on public.historico_pontos for select to authenticated using (true);
create policy historico_pontos_escrever on public.historico_pontos for insert to authenticated
  with check (public.perfil_atual() in ('administrador','operador'));
create policy perfis_ler on public.perfis for select to authenticated
  using (user_id = auth.uid() or public.perfil_atual() = 'administrador');
create policy perfis_administrar on public.perfis for all to authenticated
  using (public.perfil_atual() = 'administrador')
  with check (public.perfil_atual() = 'administrador');
create policy despesas_ler on public.despesas_mensais for select to authenticated using (true);
create policy despesas_escrever on public.despesas_mensais for all to authenticated
  using (public.perfil_atual() in ('administrador','operador'))
  with check (public.perfil_atual() in ('administrador','operador'));

commit;
