begin;

alter table public.pontos
  add column if not exists situacao_operacional text not null default 'ativo',
  add column if not exists situacao_alterada_em timestamptz,
  add column if not exists situacao_alterada_por uuid references auth.users(id) on delete set null,
  add column if not exists desativado_em timestamptz,
  add column if not exists versao_operacional bigint not null default 1;

alter table public.pontos
  drop constraint if exists pontos_situacao_operacional_check,
  add constraint pontos_situacao_operacional_check
    check (situacao_operacional in ('ativo', 'desativado')),
  drop constraint if exists pontos_desativacao_consistente_check,
  add constraint pontos_desativacao_consistente_check
    check (
      (situacao_operacional = 'ativo' and desativado_em is null)
      or (situacao_operacional = 'desativado' and desativado_em is not null)
    );

create table if not exists public.solicitacoes_status_ponto (
  id bigint generated by default as identity primary key,
  ponto_id bigint not null references public.pontos(id) on delete restrict,
  ponto_nome text not null,
  gerente text not null,
  acao text not null check (acao = 'desativar'),
  motivo text not null check (char_length(btrim(motivo)) between 5 and 1000),
  status text not null default 'pendente'
    check (status in ('pendente', 'aprovada', 'rejeitada')),
  solicitado_por uuid not null references auth.users(id) on delete restrict,
  solicitado_por_perfil text not null check (solicitado_por_perfil = 'gerente'),
  solicitado_em timestamptz not null default now(),
  decidido_por uuid references auth.users(id) on delete restrict,
  decidido_por_perfil text check (decidido_por_perfil = 'administrador'),
  decidido_em timestamptz,
  motivo_decisao text,
  versao_ponto bigint not null,
  constraint solicitacoes_status_ponto_decisao_check check (
    (status = 'pendente' and decidido_por is null and decidido_em is null)
    or (status in ('aprovada', 'rejeitada') and decidido_por is not null and decidido_em is not null)
  )
);

create unique index if not exists solicitacoes_status_ponto_pendente_uidx
  on public.solicitacoes_status_ponto (ponto_id, acao)
  where status = 'pendente';

create index if not exists solicitacoes_status_ponto_ponto_idx
  on public.solicitacoes_status_ponto (ponto_id, solicitado_em desc);

create table if not exists public.historico_status_pontos (
  id bigint generated by default as identity primary key,
  ponto_id bigint not null references public.pontos(id) on delete restrict,
  solicitacao_id bigint references public.solicitacoes_status_ponto(id) on delete restrict,
  acao text not null check (acao in ('desativacao_aprovada', 'desativacao_rejeitada', 'reativacao')),
  estado_anterior text not null check (estado_anterior in ('ativo', 'desativado')),
  estado_posterior text not null check (estado_posterior in ('ativo', 'desativado')),
  motivo text not null check (char_length(btrim(motivo)) between 5 and 1000),
  usuario_id uuid not null references auth.users(id) on delete restrict,
  perfil text not null check (perfil = 'administrador'),
  criado_em timestamptz not null default now()
);

create index if not exists historico_status_pontos_ponto_idx
  on public.historico_status_pontos (ponto_id, criado_em desc);

alter table public.solicitacoes_status_ponto enable row level security;
alter table public.historico_status_pontos enable row level security;

create policy solicitacoes_status_ponto_ler
on public.solicitacoes_status_ponto for select to authenticated
using (
  private.perfil_atual() = 'administrador'
  or (
    private.perfil_atual() = 'gerente'
    and exists (
      select 1 from public.perfis pf
      where pf.user_id = auth.uid()
        and pf.perfil = 'gerente'
        and (
          public.solicitacoes_status_ponto.gerente = any(coalesce(pf.rotas_permitidas, array[]::text[]))
          or lower(coalesce(nullif(pf.gerente_nome, ''), pf.nome, '')) = lower(public.solicitacoes_status_ponto.gerente)
        )
    )
  )
);

create policy historico_status_pontos_ler
on public.historico_status_pontos for select to authenticated
using (
  private.perfil_atual() = 'administrador'
  or (
    private.perfil_atual() = 'gerente'
    and exists (
      select 1
      from public.pontos pt
      join public.perfis pf on pf.user_id = auth.uid()
      where pt.id = public.historico_status_pontos.ponto_id
        and pf.perfil = 'gerente'
        and (
          pt.gerente = any(coalesce(pf.rotas_permitidas, array[]::text[]))
          or lower(coalesce(nullif(pf.gerente_nome, ''), pf.nome, '')) = lower(pt.gerente)
        )
    )
  )
);

create or replace function private.proteger_situacao_operacional_ponto()
returns trigger
language plpgsql
set search_path = public, private, pg_temp
as $$
begin
  if new.situacao_operacional is distinct from old.situacao_operacional
     or new.situacao_alterada_em is distinct from old.situacao_alterada_em
     or new.situacao_alterada_por is distinct from old.situacao_alterada_por
     or new.desativado_em is distinct from old.desativado_em
     or new.versao_operacional is distinct from old.versao_operacional then
    if current_setting('stockon.ciclo_ponto_rpc', true) is distinct from 'permitido' then
      raise exception using errcode = '42501', message = 'O ciclo operacional do ponto só pode ser alterado pelas operações autorizadas.';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists proteger_situacao_operacional_ponto on public.pontos;
create trigger proteger_situacao_operacional_ponto
before update on public.pontos
for each row execute function private.proteger_situacao_operacional_ponto();

create or replace function private.validar_destino_equipamento_operacional()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_situacao text;
begin
  if nullif(btrim(coalesce(new.localizacao, '')), '') is null then return new; end if;

  select p.situacao_operacional into v_situacao
  from public.pontos p
  where lower(btrim(p.nome_fantasia)) = lower(btrim(new.localizacao))
  for key share;

  if v_situacao = 'desativado' then
    raise exception using errcode = '55000', message = 'Não é permitido vincular equipamento a um ponto desativado.';
  end if;
  return new;
end;
$$;

drop trigger if exists validar_destino_equipamento_operacional on public.equipamentos;
create trigger validar_destino_equipamento_operacional
before insert or update of localizacao on public.equipamentos
for each row execute function private.validar_destino_equipamento_operacional();

create or replace function private.validar_competencia_ponto_ativo()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_desativado_em timestamptz;
begin
  if new.ponto_id is null then return new; end if;

  select p.desativado_em into v_desativado_em
  from public.pontos p where p.id = new.ponto_id;

  if v_desativado_em is not null
     and date_trunc('month', new.competencia::date) > date_trunc('month', v_desativado_em at time zone 'America/Sao_Paulo') then
    raise exception using errcode = '23514', message = 'Não é permitido lançar despesa posterior à desativação do ponto.';
  end if;
  return new;
end;
$$;

drop trigger if exists validar_competencia_ponto_ativo on public.despesas_mensais;
create trigger validar_competencia_ponto_ativo
before insert or update of ponto_id, competencia on public.despesas_mensais
for each row execute function private.validar_competencia_ponto_ativo();

create or replace function public.solicitar_desativacao_ponto(p_ponto_id bigint, p_motivo text)
returns public.solicitacoes_status_ponto
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_ponto public.pontos%rowtype;
  v_resultado public.solicitacoes_status_ponto%rowtype;
begin
  if auth.uid() is null or private.perfil_atual() <> 'gerente' then
    raise exception using errcode = '42501', message = 'Somente gerente pode solicitar a desativação.';
  end if;
  if char_length(btrim(coalesce(p_motivo, ''))) < 5 then
    raise exception using errcode = '22023', message = 'Informe um motivo com pelo menos 5 caracteres.';
  end if;

  select * into strict v_ponto from public.pontos where id = p_ponto_id for update;
  if v_ponto.situacao_operacional <> 'ativo' then
    raise exception using errcode = '55000', message = 'O ponto não está ativo.';
  end if;
  if not exists (
    select 1 from public.perfis pf
    where pf.user_id = auth.uid() and pf.perfil = 'gerente'
      and (
        v_ponto.gerente = any(coalesce(pf.rotas_permitidas, array[]::text[]))
        or lower(coalesce(nullif(pf.gerente_nome, ''), pf.nome, '')) = lower(v_ponto.gerente)
      )
  ) then
    raise exception using errcode = '42501', message = 'Ponto fora do escopo do gerente.';
  end if;

  insert into public.solicitacoes_status_ponto (
    ponto_id, ponto_nome, gerente, acao, motivo, solicitado_por,
    solicitado_por_perfil, versao_ponto
  ) values (
    v_ponto.id, v_ponto.nome_fantasia, v_ponto.gerente, 'desativar', btrim(p_motivo),
    auth.uid(), 'gerente', v_ponto.versao_operacional
  ) returning * into v_resultado;
  return v_resultado;
exception
  when unique_violation then
    raise exception using errcode = '23505', message = 'Já existe uma solicitação de desativação pendente para este ponto.';
end;
$$;

create or replace function public.decidir_desativacao_ponto(
  p_solicitacao_id bigint,
  p_aprovar boolean,
  p_motivo_decisao text default null
)
returns public.solicitacoes_status_ponto
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_solicitacao public.solicitacoes_status_ponto%rowtype;
  v_ponto public.pontos%rowtype;
  v_equipamentos text;
begin
  if auth.uid() is null or private.perfil_atual() <> 'administrador' then
    raise exception using errcode = '42501', message = 'Somente administrador pode decidir a solicitação.';
  end if;
  if not p_aprovar and char_length(btrim(coalesce(p_motivo_decisao, ''))) < 5 then
    raise exception using errcode = '22023', message = 'Informe o motivo da rejeição.';
  end if;

  select * into strict v_solicitacao
  from public.solicitacoes_status_ponto where id = p_solicitacao_id for update;
  if v_solicitacao.status <> 'pendente' then
    raise exception using errcode = '55000', message = 'Esta solicitação já foi decidida.';
  end if;

  select * into strict v_ponto from public.pontos where id = v_solicitacao.ponto_id for update;
  if v_ponto.situacao_operacional <> 'ativo'
     or v_ponto.versao_operacional <> v_solicitacao.versao_ponto then
    raise exception using errcode = '40001', message = 'O ponto foi alterado após a solicitação. Revise antes de continuar.';
  end if;

  if p_aprovar then
    select string_agg(e.nome, ', ' order by e.nome) into v_equipamentos
    from public.equipamentos e
    where nullif(btrim(e.localizacao), '') is not null
      and lower(btrim(e.localizacao)) = lower(btrim(v_ponto.nome_fantasia));
    if v_equipamentos is not null then
      raise exception using errcode = '55000',
        message = 'Remaneje ou disponibilize os equipamentos antes de desativar: ' || v_equipamentos;
    end if;

    perform set_config('stockon.ciclo_ponto_rpc', 'permitido', true);
    update public.pontos set
      situacao_operacional = 'desativado', situacao_alterada_em = now(),
      situacao_alterada_por = auth.uid(), desativado_em = now(),
      versao_operacional = versao_operacional + 1
    where id = v_ponto.id;

    update public.solicitacoes_status_ponto set
      status = 'aprovada', decidido_por = auth.uid(), decidido_por_perfil = 'administrador',
      decidido_em = now(), motivo_decisao = nullif(btrim(coalesce(p_motivo_decisao, '')), '')
    where id = v_solicitacao.id returning * into v_solicitacao;

    insert into public.historico_status_pontos (
      ponto_id, solicitacao_id, acao, estado_anterior, estado_posterior,
      motivo, usuario_id, perfil
    ) values (
      v_ponto.id, v_solicitacao.id, 'desativacao_aprovada', 'ativo', 'desativado',
      v_solicitacao.motivo, auth.uid(), 'administrador'
    );
  else
    update public.solicitacoes_status_ponto set
      status = 'rejeitada', decidido_por = auth.uid(), decidido_por_perfil = 'administrador',
      decidido_em = now(), motivo_decisao = btrim(p_motivo_decisao)
    where id = v_solicitacao.id returning * into v_solicitacao;

    insert into public.historico_status_pontos (
      ponto_id, solicitacao_id, acao, estado_anterior, estado_posterior,
      motivo, usuario_id, perfil
    ) values (
      v_ponto.id, v_solicitacao.id, 'desativacao_rejeitada', 'ativo', 'ativo',
      btrim(p_motivo_decisao), auth.uid(), 'administrador'
    );
  end if;
  return v_solicitacao;
end;
$$;

create or replace function public.reativar_ponto(p_ponto_id bigint, p_motivo text)
returns public.pontos
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_ponto public.pontos%rowtype;
  v_resultado public.pontos%rowtype;
begin
  if auth.uid() is null or private.perfil_atual() <> 'administrador' then
    raise exception using errcode = '42501', message = 'Somente administrador pode reativar um ponto.';
  end if;
  if char_length(btrim(coalesce(p_motivo, ''))) < 5 then
    raise exception using errcode = '22023', message = 'Informe um motivo com pelo menos 5 caracteres.';
  end if;

  select * into strict v_ponto from public.pontos where id = p_ponto_id for update;
  if v_ponto.situacao_operacional <> 'desativado' then
    raise exception using errcode = '55000', message = 'O ponto não está desativado.';
  end if;

  perform set_config('stockon.ciclo_ponto_rpc', 'permitido', true);
  update public.pontos set
    situacao_operacional = 'ativo', situacao_alterada_em = now(),
    situacao_alterada_por = auth.uid(), desativado_em = null,
    versao_operacional = versao_operacional + 1
  where id = v_ponto.id returning * into v_resultado;

  insert into public.historico_status_pontos (
    ponto_id, acao, estado_anterior, estado_posterior, motivo, usuario_id, perfil
  ) values (
    v_ponto.id, 'reativacao', 'desativado', 'ativo', btrim(p_motivo), auth.uid(), 'administrador'
  );
  return v_resultado;
end;
$$;

revoke all on public.solicitacoes_status_ponto, public.historico_status_pontos from public, anon;
revoke insert, update, delete on public.solicitacoes_status_ponto, public.historico_status_pontos from authenticated;
grant select on public.solicitacoes_status_ponto, public.historico_status_pontos to authenticated, service_role;

revoke all on function public.solicitar_desativacao_ponto(bigint, text) from public, anon;
revoke all on function public.decidir_desativacao_ponto(bigint, boolean, text) from public, anon;
revoke all on function public.reativar_ponto(bigint, text) from public, anon;
grant execute on function public.solicitar_desativacao_ponto(bigint, text) to authenticated, service_role;
grant execute on function public.decidir_desativacao_ponto(bigint, boolean, text) to authenticated, service_role;
grant execute on function public.reativar_ponto(bigint, text) to authenticated, service_role;

revoke all on function private.proteger_situacao_operacional_ponto() from public, anon, authenticated;
revoke all on function private.validar_destino_equipamento_operacional() from public, anon, authenticated;
revoke all on function private.validar_competencia_ponto_ativo() from public, anon, authenticated;

commit;
