begin;

-- Baseline idempotente do schema que antecede o historico versionado.
-- Nao insere dados operacionais. Em uma base existente, apenas materializa
-- objetos ausentes; as migrations posteriores continuam sendo a fonte das
-- evolucoes desde 2026-06-13.

create table if not exists public.perfis (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nome text,
  perfil text not null default 'consulta'
    check (perfil in ('administrador', 'operador', 'gerente', 'consulta')),
  gerente_nome text not null default '',
  login_nome text,
  criado_em timestamptz not null default now()
);

create table if not exists public.pontos (
  id bigint generated by default as identity primary key,
  nome_fantasia text not null,
  nome_dono text not null default '',
  telefone text not null default '',
  gerente text not null default '',
  modalidades text[] not null default '{}',
  possui_despesa text not null default 'nao',
  valor_despesa numeric(12,2) not null default 0,
  observacao text not null default ''
);

create table if not exists public.equipamentos (
  id bigint generated by default as identity primary key,
  nome text not null,
  categoria text not null default '',
  quantidade integer not null default 1,
  status text not null default 'Disponível',
  minimo integer not null default 1,
  observacao text not null default '',
  localizacao text not null default '',
  responsavel text not null default '',
  patrimonio text not null default '',
  data_cadastro text not null default '',
  gerente_responsavel text not null default '',
  transferencia_status text not null default '',
  transferencia_enviada_em timestamptz,
  transferencia_recebida_em timestamptz,
  conserto_defeito text,
  conserto_assistencia text,
  conserto_previsao date,
  conserto_pix text,
  conserto_valor numeric(12,2) not null default 0,
  conserto_nota_nome text,
  conserto_nota_arquivo text,
  conserto_solicitado_em timestamptz,
  conserto_solicitado_por uuid references auth.users(id)
);

create table if not exists public.historico_equipamentos (
  id bigint generated by default as identity primary key,
  tipo text not null,
  item_id bigint,
  item_nome text not null default '',
  categoria text not null default '',
  qtd_antes integer not null default 0,
  qtd_depois integer not null default 0,
  responsavel text not null default '',
  observacao text not null default '',
  data text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.historico_pontos (
  id bigint generated by default as identity primary key,
  tipo text not null,
  nome text not null default '',
  gerente text not null default '',
  observacao text not null default '',
  data text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.despesas_mensais (
  id bigint generated by default as identity primary key,
  ponto_id bigint not null references public.pontos(id) on delete restrict,
  competencia date not null,
  descricao text not null,
  tipo text not null default 'fixa' check (tipo in ('fixa', 'variavel')),
  valor_previsto numeric(12,2) not null default 0,
  valor_real numeric(12,2) not null default 0,
  observacao text not null default '',
  criado_em timestamptz not null default now(),
  unique (ponto_id, competencia, descricao)
);

create table if not exists public.mensagens_internas (
  id bigint generated by default as identity primary key,
  remetente_id uuid not null references auth.users(id) on delete restrict,
  remetente_nome text not null,
  remetente_perfil text not null,
  gerente_nome text not null default '',
  destino_tipo text not null,
  mensagem text not null,
  lida_em timestamptz,
  created_at timestamptz not null default now()
);

do $baseline$
begin
  if to_regprocedure('public.criar_perfil_novo_usuario()') is null then
    execute $ddl$
      create function public.criar_perfil_novo_usuario()
      returns trigger
      language plpgsql
      security definer
      set search_path = public
      as $body$
      begin
        insert into public.perfis (user_id, nome, perfil)
        values (new.id, new.email, 'consulta')
        on conflict (user_id) do nothing;
        return new;
      end;
      $body$
    $ddl$;
  end if;

  if to_regprocedure('public.perfil_atual()') is null
     and to_regprocedure('private.perfil_atual()') is null then
    execute $ddl$
      create function public.perfil_atual()
      returns text
      language sql
      stable
      security definer
      set search_path = public
      as $body$
        select coalesce((select p.perfil from public.perfis p where p.user_id = auth.uid()), 'consulta')
      $body$
    $ddl$;
  end if;

  if to_regprocedure('public.gerente_atual()') is null
     and to_regprocedure('private.gerente_atual()') is null then
    execute $ddl$
      create function public.gerente_atual()
      returns text
      language sql
      stable
      security definer
      set search_path = public
      as $body$
        select coalesce(
          (select nullif(btrim(p.gerente_nome), '') from public.perfis p where p.user_id = auth.uid()),
          (select nullif(btrim(p.nome), '') from public.perfis p where p.user_id = auth.uid()),
          ''
        )
      $body$
    $ddl$;
  end if;

  if to_regprocedure('public.email_por_login(text)') is null then
    execute $ddl$
      create function public.email_por_login(p_login text)
      returns text
      language sql
      stable
      security definer
      set search_path = public
      as $body$
        select u.email
        from public.perfis p
        join auth.users u on u.id = p.user_id
        where lower(btrim(p.login_nome)) = lower(btrim(p_login))
        limit 1
      $body$
    $ddl$;
  end if;
end;
$baseline$;

do $baseline$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname = 'criar_perfil_ao_cadastrar_usuario'
      and tgrelid = 'auth.users'::regclass
      and not tgisinternal
  ) then
    create trigger criar_perfil_ao_cadastrar_usuario
      after insert on auth.users
      for each row execute function public.criar_perfil_novo_usuario();
  end if;
end;
$baseline$;

alter table public.perfis enable row level security;
alter table public.pontos enable row level security;
alter table public.equipamentos enable row level security;
alter table public.historico_equipamentos enable row level security;
alter table public.historico_pontos enable row level security;
alter table public.despesas_mensais enable row level security;
alter table public.mensagens_internas enable row level security;

grant usage on schema public to authenticated, service_role;
grant select, insert, update, delete on
  public.perfis,
  public.pontos,
  public.equipamentos,
  public.historico_equipamentos,
  public.historico_pontos,
  public.despesas_mensais,
  public.mensagens_internas
to authenticated;
grant usage, select on
  public.pontos_id_seq,
  public.equipamentos_id_seq,
  public.historico_equipamentos_id_seq,
  public.historico_pontos_id_seq,
  public.despesas_mensais_id_seq,
  public.mensagens_internas_id_seq
to authenticated;
do $baseline$
begin
  if to_regprocedure('public.criar_perfil_novo_usuario()') is not null then
    revoke all on function public.criar_perfil_novo_usuario() from public, anon, authenticated;
  end if;
  if to_regprocedure('public.perfil_atual()') is not null then
    revoke all on function public.perfil_atual() from public, anon;
    grant execute on function public.perfil_atual() to authenticated, service_role;
  end if;
  if to_regprocedure('public.gerente_atual()') is not null then
    revoke all on function public.gerente_atual() from public, anon;
    grant execute on function public.gerente_atual() to authenticated, service_role;
  end if;
  if to_regprocedure('public.email_por_login(text)') is not null then
    revoke all on function public.email_por_login(text) from public, authenticated;
    grant execute on function public.email_por_login(text) to anon;
  end if;
end;
$baseline$;

commit;
