begin;

create table if not exists public.prorrogacoes_despesas (
  id bigint generated by default as identity primary key,
  gerente text not null check (nullif(btrim(gerente), '') is not null),
  competencia date not null check (competencia = date_trunc('month', competencia)::date),
  expira_em timestamptz not null,
  ativo boolean not null default true,
  observacao text not null default '',
  criado_por uuid default auth.uid() references auth.users(id),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (gerente, competencia)
);

alter table public.prorrogacoes_despesas enable row level security;

drop policy if exists prorrogacoes_despesas_ler on public.prorrogacoes_despesas;
create policy prorrogacoes_despesas_ler
on public.prorrogacoes_despesas
for select
to authenticated
using (
  private.perfil_atual() = 'administrador'
  or (
    private.perfil_atual() = 'gerente'
    and lower(private.gerente_atual()) = lower(gerente)
  )
);

drop policy if exists prorrogacoes_despesas_admin_criar on public.prorrogacoes_despesas;
create policy prorrogacoes_despesas_admin_criar
on public.prorrogacoes_despesas
for insert
to authenticated
with check (private.perfil_atual() = 'administrador');

drop policy if exists prorrogacoes_despesas_admin_alterar on public.prorrogacoes_despesas;
create policy prorrogacoes_despesas_admin_alterar
on public.prorrogacoes_despesas
for update
to authenticated
using (private.perfil_atual() = 'administrador')
with check (private.perfil_atual() = 'administrador');

insert into public.prorrogacoes_despesas (gerente, competencia, expira_em, ativo, observacao)
values ('Yago', date '2026-07-01', timestamptz '2026-08-02 01:55:09+00', true, 'Prazo excepcional autorizado em 31/07/2026')
on conflict (gerente, competencia) do update set
  expira_em = excluded.expira_em,
  ativo = excluded.ativo,
  observacao = excluded.observacao,
  atualizado_em = now();

drop policy if exists despesas_prorrogacao_criar on public.despesas_mensais;
create policy despesas_prorrogacao_criar
on public.despesas_mensais
for insert
to authenticated
with check (
  private.perfil_atual() = 'gerente'
  and exists (
    select 1
    from public.prorrogacoes_despesas pd
    where pd.ativo
      and pd.expira_em > now()
      and pd.competencia = public.despesas_mensais.competencia
      and lower(pd.gerente) = lower(private.gerente_atual())
  )
  and (
    exists (
      select 1
      from public.pontos pt
      join public.perfis p on p.user_id = auth.uid()
      where pt.id = public.despesas_mensais.ponto_id
        and pt.gerente = any(coalesce(p.rotas_permitidas, array[]::text[]))
    )
    or (
      ponto_id is null
      and lower(public.despesas_mensais.gerente) = lower(private.gerente_atual())
      and exists (
        select 1 from public.perfis p
        where p.user_id = auth.uid()
          and public.despesas_mensais.rota = any(coalesce(p.rotas_permitidas, array[]::text[]))
      )
    )
  )
);

drop policy if exists despesas_prorrogacao_alterar on public.despesas_mensais;
create policy despesas_prorrogacao_alterar
on public.despesas_mensais
for update
to authenticated
using (
  private.perfil_atual() = 'gerente'
  and exists (
    select 1 from public.prorrogacoes_despesas pd
    where pd.ativo and pd.expira_em > now()
      and pd.competencia = public.despesas_mensais.competencia
      and lower(pd.gerente) = lower(private.gerente_atual())
  )
  and (
    exists (
      select 1
      from public.pontos pt
      join public.perfis p on p.user_id = auth.uid()
      where pt.id = public.despesas_mensais.ponto_id
        and pt.gerente = any(coalesce(p.rotas_permitidas, array[]::text[]))
    )
    or (
      ponto_id is null
      and lower(public.despesas_mensais.gerente) = lower(private.gerente_atual())
      and exists (
        select 1 from public.perfis p
        where p.user_id = auth.uid()
          and public.despesas_mensais.rota = any(coalesce(p.rotas_permitidas, array[]::text[]))
      )
    )
  )
)
with check (
  private.perfil_atual() = 'gerente'
  and exists (
    select 1 from public.prorrogacoes_despesas pd
    where pd.ativo and pd.expira_em > now()
      and pd.competencia = public.despesas_mensais.competencia
      and lower(pd.gerente) = lower(private.gerente_atual())
  )
  and (
    exists (
      select 1
      from public.pontos pt
      join public.perfis p on p.user_id = auth.uid()
      where pt.id = public.despesas_mensais.ponto_id
        and pt.gerente = any(coalesce(p.rotas_permitidas, array[]::text[]))
    )
    or (
      ponto_id is null
      and lower(public.despesas_mensais.gerente) = lower(private.gerente_atual())
      and exists (
        select 1 from public.perfis p
        where p.user_id = auth.uid()
          and public.despesas_mensais.rota = any(coalesce(p.rotas_permitidas, array[]::text[]))
      )
    )
  )
);

drop policy if exists despesas_prorrogacao_remover on public.despesas_mensais;
create policy despesas_prorrogacao_remover
on public.despesas_mensais
for delete
to authenticated
using (
  private.perfil_atual() = 'gerente'
  and exists (
    select 1 from public.prorrogacoes_despesas pd
    where pd.ativo and pd.expira_em > now()
      and pd.competencia = public.despesas_mensais.competencia
      and lower(pd.gerente) = lower(private.gerente_atual())
  )
  and (
    exists (
      select 1
      from public.pontos pt
      join public.perfis p on p.user_id = auth.uid()
      where pt.id = public.despesas_mensais.ponto_id
        and pt.gerente = any(coalesce(p.rotas_permitidas, array[]::text[]))
    )
    or (
      ponto_id is null
      and lower(public.despesas_mensais.gerente) = lower(private.gerente_atual())
      and exists (
        select 1 from public.perfis p
        where p.user_id = auth.uid()
          and public.despesas_mensais.rota = any(coalesce(p.rotas_permitidas, array[]::text[]))
      )
    )
  )
);

drop policy if exists despesas_yago_julho_criar on public.despesas_mensais;
drop policy if exists despesas_yago_julho_alterar on public.despesas_mensais;
drop policy if exists despesas_yago_julho_remover on public.despesas_mensais;

grant select, insert, update on public.prorrogacoes_despesas to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
