begin;

create table if not exists public.solicitacoes_modalidade (
  id bigint generated by default as identity primary key,
  ponto_id bigint references public.pontos(id) on delete cascade,
  ponto_nome text not null,
  gerente text not null,
  rota text not null,
  modalidade text not null,
  acao text not null check (acao in ('bloquear', 'desbloquear')),
  detalhe text not null default '',
  status text not null default 'pendente' check (status in ('pendente', 'concluida')),
  criado_por uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now(),
  concluido_em timestamptz
);

alter table public.solicitacoes_modalidade enable row level security;

drop policy if exists solicitacoes_modalidade_ler on public.solicitacoes_modalidade;
drop policy if exists solicitacoes_modalidade_criar on public.solicitacoes_modalidade;
drop policy if exists solicitacoes_modalidade_atualizar on public.solicitacoes_modalidade;

create policy solicitacoes_modalidade_ler
on public.solicitacoes_modalidade
for select
to authenticated
using (
  public.perfil_atual() = 'administrador'
  or exists (
    select 1
    from public.perfis p
    where p.user_id = auth.uid()
      and p.perfil = 'gerente'
      and (
        public.solicitacoes_modalidade.rota = any(coalesce(p.rotas_permitidas, array[]::text[]))
        or lower(coalesce(nullif(p.gerente_nome, ''), p.nome, '')) = lower(public.solicitacoes_modalidade.gerente)
      )
  )
);

create policy solicitacoes_modalidade_criar
on public.solicitacoes_modalidade
for insert
to authenticated
with check (
  public.perfil_atual() = 'gerente'
  and criado_por = auth.uid()
  and exists (
    select 1
    from public.perfis p
    where p.user_id = auth.uid()
      and p.perfil = 'gerente'
      and (
        public.solicitacoes_modalidade.rota = any(coalesce(p.rotas_permitidas, array[]::text[]))
        or lower(coalesce(nullif(p.gerente_nome, ''), p.nome, '')) = lower(public.solicitacoes_modalidade.gerente)
      )
  )
);

create policy solicitacoes_modalidade_atualizar
on public.solicitacoes_modalidade
for update
to authenticated
using (public.perfil_atual() = 'administrador')
with check (public.perfil_atual() = 'administrador');

commit;
